name: courier_rider
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sizer: ^2.0.15
  http: ^0.13.5
  hexcolor: ^3.0.1
  flex_color_scheme: ^6.1.2
  getwidget: ^3.0.1
  animated: ^2.0.0
  delayed_display: ^2.0.0
  shared_preferences: ^2.0.20
  equatable: ^2.0.5
  overlay_loader_with_app_icon: ^0.0.3
  otp_text_field: ^1.1.3
  intl: ^0.18.0
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.1.10
  maps_launcher: ^2.2.0
  flutter_datetime_picker: ^1.5.1
  geolocator: ^9.0.2
  web_socket_channel: ^2.4.0
  web_socket_client: ^0.1.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/image/
    - assets/actionImage/
